.\" (c) 2007 Miriam Ruiz <little_miry@yahoo.es>
.\" 
.\" This document is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This package is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this package; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
.TH "SnowballZ" "6" "June 2007" "" "Games"
.SH "NAME"
snowballz \- fun RTS game featuring snowball fights with penguins
.SH "SYNOPSIS"
.B snowballz
.SH "DESCRIPTION"
Take command of your army of penguins as you blaze your path to victory!
.PP 
March through snow laden forests to conqueror new frontiers and grow your small army. Ambush enemy lines with blasts of freezing snowballs. But don't neglect your home, invaders are just over the next snow drift!
.PP 
Gather fish for your cold penguins to munch on as they warm up in your cozy igloo.
.PP 
It's a snowy world you don't want to miss!
.PP 
.SH "REQUIREMENTS"
You will need to make sure that you have all of these items installed on your system. If you use linux most of these will be in your distribution's repository.
.PP 
  * Python 2.4
  * pygame
  * PyOpenGL
  * Numeric
  * PIL
.PP 
.SH "CONTROLS"
You can control snowballers (not workers) by selecting them (ether by clicking on them or dragging a select box around them) and right clicking to tell them to do something.
.PP 
Left click to select, right click to perform an action. If you right click somewhere, they will move and stay there until they get cold or you tell them to go somewhere else. Snowballers that don't have any orders (they are cleared when they get cold), will walk around their home igloo. Penguins get cold when hit by snowballs.
.PP 
To disband your units (make them go stray around their igloos) by pressing the **o** key. You can also make your penguins run somewhere without stopping to throw at enemies by middle clicking instead of right clicking.
.PP 
You can move the screen around by using the arrow keys or **aswd** keys. Hold down on space to bring up a nice big minimap.
.PP 
Zoom in and out with the page\-up and page\-down keys. Note that for now it might be a little slow when zoomed out!
.PP 
.SH "CHAT"
To send a chat message, first press enter to bring up the chat box. Once up, simply type your message and press enter again. Your message will be sent to everyone! If you want to send to just one person, you can type::
.PP 
 >playername Hi playername! This is a privet message!
.PP 
playername being the name of the person you want to send a chat message to.
.PP 
There is tab completeion too! So you can type ">" then hit TAB to see all players that you can send a privet chat to. Two useful shortcuts you can use are the "," and "." keys. Press the period when you aren't in chatmode and it will bring up the chatbox to send a message to the last person that sent a privet chat to you. The "," works the same way except to the last person you sent a privet chat to.
.PP 
If you ever have a bunch of chats on your screen that you just want to get rid of, you can press the **c** key to clear them all.
.PP 
.SH "TAKEOVER"
If you tell a snowballer to move to an enemy igloo (by right clicking on it), it will run without stopping until it gets into it. If you can hold the enemy igloo for 30 seconds, it, the region, and all penguins belonging to the igloo will become yours.
.PP 
Be carefull though, if an enemy snowballer enters the igloo you are taking over, your penguin will be shown the door with a cold snowball in his face.
.PP 
Penguins (on ether side) can not exit an igloo that is in the middle of a takeover.
.PP 
When an igloo is being taken over, the penguins belonging to that igloo will go bananas. The workers will just run around in a panic and the snowballers will rush to try to save it in time not listening to your orders. (actually, the workers don't do that yet, but they will!)
.PP 
On the bottom right corner of igloos there is a marker designating which player that igloo belongs to. When an igloo is in jeopardy (being taken over), that marker turns multicolored.
.PP 
.SH "WARMING AND REASSIGNING"
When a penguin gets cold from being hit with too many snowballs, it will run madly back to it's home igloo (you won't be able to control it again until it's warm). Once back in it's igloo, it can take up to 40 seconds to get warmed up (depending on how cold it was when going in)! It also requires a fish before it will go back out if it's warmth was below a certain level (your workers will automatically gather fish).
.PP 
If you tell a snowballer to enter one of your igloos (again, by right clicking on it), it will enter it. Immediately after entering, the igloo you told it to go to becomes it's home igloo. If it is all the way warm, it will exit immediately. Otherwise it will stay for a snack and warm up.
.PP 
.SH "TERRAIN TYPES"
In the game you will come across two different types of land; Ice and snow. Really the only difference between the two is that snowballers can only create snowballs on snow (not ice).
.PP 
Try to catch your enemy on the the ice with your snowballers standing on the snow. If you can, you'll cream 'em!
.PP 
.SH "TIPS"
When one of your penguins enters their igloo and is only a little bit cold, they won't eat a fish but will still get warm. The colder the penguin, the longer they take to warm up!
.PP 
You can gain a strategic advantage in a snowball fight if your penguins are among some trees while your opponents aren't. Snowballs that hit trees have no effect on surrounding penguins.
.PP 
Normally, a snowball that lands next to a penguin brings it's warmth down just a little while a direct hit will bring it down a lot. If your penguins get close enough to their enemy, they are much more accurate!
.PP 
One mean strategy you can use against your opponent when they are between your army and their own igloo is to send one of your penguins into their igloo. This will make your penguin run without stop towards their igloo distracting the enemy. This will give your snowballers a chance to get a handle on the situation. If your snowballer does manage to get into their igloo, all of their snowballers will panic and race to it, and stop throwing their snowballs!
.PP 
.SH "CREDITS"
The game has been developed by:
.PP 
  * Joey Marshall <web@joey101.net>
    \- lead programmer
    \- designer
    \- gfx
.PP 
  * Matthew Marshall <matthew@matthewmarshall.org>
    \- programming
    \- networking
.PP 
This man page has been made by Miriam Ruiz <little_miry@yahoo.es>, based in the README file that comes along with the game.
.SH "SEE ALSO"
You can find more information at http://joey101.net/snowballz/
